In [3]:
import numpy as np
a = np.array(list(range(9))).reshape(
3,3
)

In [3]:
import numpy as np
t = np.array([1, 2, 3])
t2 = np.array([2, 2, 4])
np.concatenate((t-t2).ravel())

ValueError: zero-dimensional arrays cannot be concatenated

In [6]:

print(a[:-1,0])

[0 3]


In [7]:
b = np.array([1,2,3])
c = np.array([4,5,6])
b*c

array([ 4, 10, 18])

In [9]:
ee = np.zeros((3,3))
ee[:-1,-1] = b[:-1]*c[:-1]
ee

array([[ 0.,  0.,  4.],
       [ 0.,  0., 10.],
       [ 0.,  0.,  0.]])

In [3]:
import numpy as np
R = np.arange(9).reshape((3,3))
t = np.array([1, 2, 3])
l = np.hstack((R, t[:, np.newaxis]))

l

array([[0, 1, 2, 1],
       [3, 4, 5, 2],
       [6, 7, 8, 3]])